import { toKebabCase } from "./parse";
import type { CommandGroup } from "./types";

// ── Zsh completion generation ────────────────────────────────────────────────────
//
// Walks the declarative command tree and emits a self-contained `#compdef`
// function: groups at depth 1, that group's commands at depth 2, and the
// selected command's flags at depth 3. Generated by `tools completion zsh`.

/** Strip characters that would break a zsh _describe/_arguments spec. */
function sanitize(text: string): string {
  return text.replace(/['`$]/g, "").replace(/:/g, " -").replace(/[[\]]/g, "");
}

/** Derive a valid zsh function name from the program name. */
function functionName(programName: string): string {
  return `_${programName.replace(/[^a-zA-Z0-9_]/g, "_")}`;
}

/** Pick the program name a completion script should bind to (e.g. "tools"). */
export function completionProgramName(binName: string): string {
  const parts = binName.trim().split(/\s+/);
  return parts[parts.length - 1] || "tools";
}

export function generateZshCompletion(groups: CommandGroup[], programName: string): string {
  const fn = functionName(programName);
  const lines: string[] = [
    `#compdef ${programName}`,
    `# zsh completion for ${programName} — regenerate with: ${programName} completion zsh`,
    "",
    `${fn}() {`,
    "  local -a _groups",
    "  _groups=(",
    ...groups.map((g) => `    '${g.name}:${sanitize(g.description)}'`),
    "  )",
    "  if (( CURRENT == 2 )); then",
    "    _describe 'group' _groups",
    "    return",
    "  fi",
    '  case "${words[2]}" in',
  ];

  for (const group of groups) {
    lines.push(
      `    ${group.name})`,
      "      local -a _cmds",
      "      _cmds=(",
      ...group.commands.map((c) => `        '${c.name}:${sanitize(c.description)}'`),
      "      )",
      "      if (( CURRENT == 3 )); then",
      "        _describe 'command' _cmds",
      "        return",
      "      fi",
      '      case "${words[3]}" in',
    );
    for (const cmd of group.commands) {
      const specs = [
        ...cmd.flags.map((f) => `'--${toKebabCase(f.name)}[${sanitize(f.description)}]'`),
        "'--help[Show help]'",
        "'--interactive[Launch interactive TUI]'",
      ];
      lines.push(`        ${cmd.name})`, `          _arguments ${specs.join(" ")} ;;`);
    }
    lines.push("      esac", "      ;;");
  }

  lines.push("  esac", "}", "", `${fn} "$@"`);
  return lines.join("\n");
}
